#!/usr/bin/env python3
"""
Check that the Content-Security-Policy-Report-Only header value (built from
chaos_tester_csp_style_hashes.py + the boilerplate directives in app.py) fits
under Google Frontend's per-header byte limit.

Background: GFE silently strips response headers whose value exceeds ~8192
bytes. The Report-Only header on chaos_tester is currently the binding
constraint because every inline `style="..."` attribute on the site
contributes a sha256 hash to that header's `style-src-attr 'unsafe-hashes'`
allowlist.

This script reconstructs the EXACT header value app.py emits, measures it,
and exits non-zero if it exceeds the configured threshold (default 7,800
bytes — leaves ~400 bytes of margin under the 8,192-byte hard limit).

Run from the chaos_tester repo root:

    python3 scripts/check_csp_header_size.py            # default 7,800-byte threshold
    python3 scripts/check_csp_header_size.py --max 8192 # tighter, no margin
    python3 scripts/check_csp_header_size.py --report   # print details, never fail

CI usage: invoked as a step in .github/workflows/deploy-cloud-run.yml right
after compute_style_hashes.py --check.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_MAX_BYTES = 8_100
GFE_HARD_LIMIT = 8_192


def load_hashes(repo_root: Path) -> list[str]:
    """Read the autogenerated hash file and return the sorted list of tokens."""
    p = repo_root / "chaos_tester_csp_style_hashes.py"
    if not p.exists():
        return []
    blob = p.read_text(encoding="utf-8")
    return sorted(set(re.findall(r"'sha256-[A-Za-z0-9+/=]+'", blob)))


def build_header_value(hashes: list[str]) -> str:
    """Reconstruct the enforced Content-Security-Policy header EXACTLY as
    app.py emits it after Phase 4-B. This is the only CSP header on the site
    now (the prior Report-Only header was retired with Phase 4-B)."""
    return (
        "default-src 'self'; "
        "script-src 'self' https://cdnjs.cloudflare.com https://gc.zgo.at https://maps.googleapis.com; "
        "style-src-elem 'self'; "
        "style-src-attr 'self' 'unsafe-hashes' " + " ".join(hashes) + "; "
        "img-src 'self' data: blob: https://maps.googleapis.com https://maps.gstatic.com; "
        "connect-src 'self' https://website-auditor.io https://website-auditor.goatcounter.com https://maps.googleapis.com; "
        "font-src 'self' https://fonts.gstatic.com;"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--max",
        type=int,
        default=DEFAULT_MAX_BYTES,
        help=f"Maximum allowed header byte length (default: {DEFAULT_MAX_BYTES}; "
             f"GFE hard limit: {GFE_HARD_LIMIT}).",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="Print details and exit 0 regardless of size (informational only).",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root (defaults to the parent of scripts/).",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    hashes = load_hashes(repo_root)
    if not hashes:
        print(
            "WARN: chaos_tester_csp_style_hashes.py is empty or missing. "
            "Run scripts/compute_style_hashes.py first.",
            file=sys.stderr,
        )

    value = build_header_value(hashes)
    n = len(value)
    headroom_target = args.max - n
    headroom_gfe = GFE_HARD_LIMIT - n

    print(f"  Inline-style hashes:        {len(hashes)}")
    print(f"  Report-Only header bytes:   {n:,}")
    print(f"  Configured limit:           {args.max:,}")
    print(f"  Headroom under limit:       {headroom_target:+,}")
    print(f"  GFE hard limit:             {GFE_HARD_LIMIT:,}")
    print(f"  Headroom under GFE limit:   {headroom_gfe:+,}")

    if args.report:
        return 0

    if n > args.max:
        print(
            "\nFAIL: Report-Only header exceeds the configured budget.\n"
            "  Either:\n"
            "    1. Refactor more inline style attributes into static/css/utilities.css\n"
            "       classes (run scripts/audit_inline_styles.py templates to see the\n"
            "       top remaining patterns), or\n"
            "    2. Bump --max in this script (and the workflow caller) up to a higher\n"
            "       budget — but never above 8,192 since that's GFE's hard limit and\n"
            "       headers above that are silently stripped from responses.",
            file=sys.stderr,
        )
        return 1

    print("\nOK: header fits under the configured budget.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
