#!/usr/bin/env python3
"""
Compute sha256 CSP hashes for every inline `style="..."` attribute body
across `templates/`. Emits a Python module that `app.py` imports and
splices into the `style-src-attr` CSP directive via `'unsafe-hashes'`.

Run from the chaos_tester repo root:

    python3 scripts/compute_style_hashes.py

Writes to:

    chaos_tester_csp_style_hashes.py

Per CSP3 §6.6.1.4 (External Hash) and §7.7 (Strict Hashes Source), an
inline `style="..."` attribute is permitted under
`style-src-attr 'unsafe-hashes' 'sha256-<base64>'` if the sha256 of the
exact byte sequence between the quotes matches.

This script is run by the Cloud Run deploy workflow before
`gcloud run deploy`, so the hash list always tracks the most-recently-
committed templates. Templates that introduce a new inline style
without a matching hash will trigger a CSP report-only violation in
DevTools — that's the operational signal to re-run the script or move
the new value into a class.

Pen-test 2026-05-05 finding WA-2026-05-05-02 phase 4.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import re
import sys
from pathlib import Path


STYLE_RE = re.compile(r'style="([^"]*)"', re.DOTALL)


def find_template_files(repo_root: Path) -> list[Path]:
    """Every `*.html` under templates/. Sorted for deterministic output."""
    d = repo_root / "templates"
    if not d.is_dir():
        return []
    return sorted(d.rglob("*.html"))


def hash_inline_styles(html: str) -> list[str]:
    """Return the CSP `'sha256-<base64>'` token for every inline style attr."""
    out: list[str] = []
    for m in STYLE_RE.finditer(html):
        body = m.group(1)
        # CSP hashes the exact bytes between the quotes — no
        # normalization, no whitespace stripping. The browser does the
        # same. (https://www.w3.org/TR/CSP3/#external-hash)
        digest = hashlib.sha256(body.encode("utf-8")).digest()
        out.append(f"'sha256-{base64.b64encode(digest).decode('ascii')}'")
    return out


def write_module(repo_root: Path, hashes: list[str]) -> Path:
    sorted_unique = sorted(set(hashes))
    out = repo_root / "chaos_tester_csp_style_hashes.py"
    body = [
        '"""',
        "AUTOGENERATED by scripts/compute_style_hashes.py — do not hand-edit.",
        "",
        "CSP sha256 hashes for every inline `style=\"...\"` attribute body in",
        "templates/. Imported by app.py and joined into the style-src-attr",
        "CSP directive via 'unsafe-hashes'.",
        "",
        f"Last regenerated for {len(sorted_unique)} unique attribute bodies.",
        "",
        "Pen-test 2026-05-05 finding WA-2026-05-05-02 phase 4.",
        '"""',
        "",
        "STYLE_HASHES: list[str] = [",
    ]
    for h in sorted_unique:
        body.append(f"    {h!r},")
    body.append("]")
    body.append("")
    out.write_text("\n".join(body), encoding="utf-8")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root (defaults to the parent of scripts/).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Exit non-zero if chaos_tester_csp_style_hashes.py is out of "
            "date relative to the current templates/. Use in CI."
        ),
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    files = find_template_files(repo_root)
    if not files:
        print("ERROR: no template files found under templates/", file=sys.stderr)
        return 2

    all_hashes: list[str] = []
    per_file: dict[str, int] = {}
    for f in files:
        html = f.read_text(encoding="utf-8")
        hs = hash_inline_styles(html)
        if hs:
            per_file[str(f.relative_to(repo_root))] = len(hs)
        all_hashes.extend(hs)

    out = repo_root / "chaos_tester_csp_style_hashes.py"
    sorted_unique = sorted(set(all_hashes))

    if args.check:
        if not out.exists():
            print(
                "FAIL: chaos_tester_csp_style_hashes.py does not exist.\n"
                "Regenerate: python3 scripts/compute_style_hashes.py",
                file=sys.stderr,
            )
            return 1
        existing = out.read_text(encoding="utf-8")
        existing_hashes = sorted(re.findall(r"'sha256-[A-Za-z0-9+/=]+'", existing))
        if existing_hashes != sorted_unique:
            print(
                f"FAIL: hash list out of date.\n"
                f"  expected {len(sorted_unique)} hashes, "
                f"found {len(existing_hashes)}.\n"
                f"  Regenerate: python3 scripts/compute_style_hashes.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: chaos_tester_csp_style_hashes.py up to date ({len(sorted_unique)} hashes)")
        return 0

    out_path = write_module(repo_root, all_hashes)
    print(
        f"wrote {out_path.relative_to(repo_root)} — "
        f"{len(sorted_unique)} unique hashes "
        f"across {sum(per_file.values())} inline style attributes "
        f"in {len(per_file)} files"
    )
    for fname, n in sorted(per_file.items()):
        print(f"  {n:4d}  {fname}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
